# Generated by Django 5.0.4 on 2024-05-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Make your title concise.', max_length=100)),
                ('content', models.TextField(help_text='Start writing in this field')),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
            ],
            options={
                'ordering': ['last_name', 'given_name'],
            },
        ),
    ]
