# Generated by Django 5.0.4 on 2024-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['given_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('ENG', 'ENGLISH'), ('TAG', 'TAGALOG'), ('TAGLISH', 'TAGALOG-ENGLISH'), ('SPA', 'SPANISH'), ('GER', 'GERMAN')], default='ENG', max_length=20),
        ),
    ]
