# Generated by Django 5.0.4 on 2024-09-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_author_options_remove_author_date_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Publish', 'PUBLISH'), ('Draft', 'DRAFT')], default='DRAFT', max_length=20),
        ),
    ]
